# .circleci/config.yml
version: 2.1

orbs:
  macos: circleci/macos@2.3.2
  gh: circleci/github-cli@2.0

commands:
  configure-gpg:
    steps:
      - run:
          name: Import GPG Key
          command: |
            hash gpg || brew install --cask gpg-suite-no-mail
            echo -e $GPG_PRIVATE_KEY | gpg --batch --import
      - run:
          name: Configure Git for Signing Commits
          command: |
            git config --global user.signingkey $GPG_KEY_ID
            git config --global commit.gpgsign true
            git config --global user.email 'devops@kustomer.com'
            git config --global user.name "kustomer-builds"

jobs:
  publish-to-cocoapods:
    macos:
      xcode: 14.3
    steps:
      - checkout
      - macos/switch-ruby:
          version: '2.7'
      - run:
          name: Publish to Cocoa Pods
          command: |
            echo "Publish to CocoaPods"
      - persist_to_workspace:
          root: ~/project
          paths: ./*

workflows:
  publish_to_cocoapods:
    jobs:
      - publish-to-cocoapods